# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MM_mainwin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 1031, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.gametype = QtWidgets.QTextEdit(self.layoutWidget)
        self.gametype.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.gametype.setFont(font)
        self.gametype.setAcceptDrops(False)
        self.gametype.setInputMethodHints(QtCore.Qt.ImhNone)
        self.gametype.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gametype.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gametype.setReadOnly(True)
        self.gametype.setObjectName("gametype")
        self.gridLayout.addWidget(self.gametype, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.secrettable = QtWidgets.QTableWidget(self.layoutWidget)
        self.secrettable.setMaximumSize(QtCore.QSize(16777215, 40))
        self.secrettable.setRowCount(0)
        self.secrettable.setColumnCount(5)
        self.secrettable.setObjectName("secrettable")
        self.secrettable.horizontalHeader().setVisible(False)
        self.secrettable.horizontalHeader().setDefaultSectionSize(80)
        self.secrettable.verticalHeader().setDefaultSectionSize(20)
        self.secrettable.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.secrettable, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.guesstable = QtWidgets.QTableWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.guesstable.setFont(font)
        self.guesstable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.guesstable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.guesstable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.guesstable.setRowCount(0)
        self.guesstable.setColumnCount(6)
        self.guesstable.setObjectName("guesstable")
        self.guesstable.horizontalHeader().setVisible(False)
        self.guesstable.horizontalHeader().setCascadingSectionResizes(True)
        self.guesstable.horizontalHeader().setHighlightSections(False)
        self.guesstable.horizontalHeader().setMinimumSectionSize(100)
        self.guesstable.verticalHeader().setVisible(False)
        self.guesstable.verticalHeader().setCascadingSectionResizes(True)
        self.guesstable.verticalHeader().setHighlightSections(False)
        self.guesstable.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout.addWidget(self.guesstable, 2, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.newgame_b = QtWidgets.QPushButton(self.layoutWidget)
        self.newgame_b.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.newgame_b.setFont(font)
        self.newgame_b.setObjectName("newgame_b")
        self.verticalLayout.addWidget(self.newgame_b)
        self.submit_b = QtWidgets.QPushButton(self.layoutWidget)
        self.submit_b.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.submit_b.setFont(font)
        self.submit_b.setObjectName("submit_b")
        self.verticalLayout.addWidget(self.submit_b)
        self.next_b = QtWidgets.QPushButton(self.layoutWidget)
        self.next_b.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.next_b.setFont(font)
        self.next_b.setObjectName("next_b")
        self.verticalLayout.addWidget(self.next_b)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MasterMind"))
        self.gametype.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MasterMind</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newgame_b.setText(_translate("MainWindow", "New Game"))
        self.submit_b.setText(_translate("MainWindow", "Submit"))
        self.next_b.setText(_translate("MainWindow", "Next"))

